### ISSUE TITLE
[TODO] 20170504

### ISSUE THREAD

**Issue by zhenglaizhang** [StarfishRocks/github-walker#1]
- [ ] clone the project to local
- [ ] play with maven, try `mvn test` and other commands
- [ ] import the project to intellij idea
